
steps: 
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ["SERVICE_ACCOUNT"]
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p /workspace/secrets && echo $$SERVICE_ACCOUNT > /workspace/secrets/api_key.json']
  - name: gcr.io/cloud-builders/docker
    id: build
    entrypoint: 'bash'
    env:
      - "TAG_NAME=$TAG_NAME"
    args: 
      - -c
      - |
        docker build -f client/fttt-build.dockerfile -t gcr.io/$PROJECT_ID/test-james-fe:0.0.1 --build-arg "GH_TAG=$TAG_NAME" .
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT/versions/latest
    env: 'SERVICE_ACCOUNT'
substitutions:
  _GCR_HOSTNAME: gcr.io
options:
  logging: CLOUD_LOGGING_ONLY
