
steps: 
  - name: gcr.io/cloud-builders/docker
    secretEnv: ["SERVICE_ACCOUNT"]
    id: build
    entrypoint: 'bash'
    args: ['-c', 'docker build -f client/fttt-build.dockerfile -t gcr.io/$PROJECT_ID/test-james-fe:0.0.1 --build-arg SERVICE_ACCOUNT=$$SERVICE_ACCOUNT .']
    volumes:
    - name: 'testvolume'
      path: '/opt/dist'
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/opt/dist/*', 'gs://flag-tic-tac-toe-client/']
    volumes:
    - name: 'testvolume'
      path: '/opt/dist'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT/versions/latest
    env: 'SERVICE_ACCOUNT'
substitutions:
  _GCR_HOSTNAME: gcr.io
options:
  logging: CLOUD_LOGGING_ONLY
