
steps: 
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --no-cache
      - -t
      - '$_GCR_HOSTNAME/$PROJECT_ID/test-james-fe:0.0.1'
      - -f
      - 'client/fttt-build.dockerfile'
      - '--build-arg=SERVICE_ACCOUNT=$$SERVICE_ACCOUNT'
      - .
    volumes:
    - name: 'testvolume'
      path: '/opt/dist'
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/opt/dist/*', 'gs://flag-tic-tac-toe-client/']
    volumes:
    - name: 'testvolume'
      path: '/opt/dist'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT/versions/1
    env: 'SERVICE_ACCOUNT'
substitutions:
  _GCR_HOSTNAME: gcr.io
options:
  logging: CLOUD_LOGGING_ONLY
