services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    command: 'yarn dev'
  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 65432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
