services:
  client:
    build: ./client
    depends_on:
      - postgres
      - go-server
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    command: 'yarn dev'
  go-server: 
    build: ./server
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./api:/go/src/app/
    command: 'go run .'
  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 65432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
