steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --no-cache
      - -t
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME'
      - .
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy backend app
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=$_PLATFORM'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--project=$PROJECT_ID'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID'
      - '--allow-unauthenticated'
      - '--max-instances=1'
    entrypoint: gcloud
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/flag-tic-tac-toe-554@flag-tic-tac-toe.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: flag-tic-tac-toe
  _GCR_HOSTNAME: gcr.io
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _TRIGGER_ID: local
